--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-nginx
  namespace: nginx
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: my-nginx
  template: 
    metadata: 
      labels: 
        run: my-nginx
    spec: 
      containers: 
        - 
         image: nginx
         name: my-nginx
         ports: 
           - 
             containerPort: 80
         resources: 
            limits: 
              cpu: 60m
            requests: 
              cpu: 50m

